
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "AND DELETE FROM IDENTIFIER INSERT INTO SELECT SET STRING UPDATE VALUES WHEREquery : select_query\n             | insert_query\n             | update_query\n             | delete_queryselect_query : SELECT '*' FROM IDENTIFIER WHERE conditionsconditions : condition\n                  | condition AND conditionscondition : IDENTIFIER '=' STRINGinsert_query : INSERT INTO IDENTIFIER '(' IDENTIFIER ')' VALUES '(' values ')' values : STRING\n              | STRING ',' valuesupdate_query : UPDATE IDENTIFIER SET set_values WHERE conditionsset_values : IDENTIFIER '=' STRING\n                  | IDENTIFIER '=' STRING ',' set_valuesdelete_query : DELETE FROM IDENTIFIER WHERE conditions"
    
_lr_action_items = {'SELECT':([0,],[6,]),'INSERT':([0,],[7,]),'UPDATE':([0,],[8,]),'DELETE':([0,],[9,]),'$end':([1,2,3,4,5,28,29,30,33,38,39,44,],[0,-1,-2,-3,-4,-15,-6,-5,-12,-8,-7,-9,]),'*':([6,],[10,]),'INTO':([7,],[11,]),'IDENTIFIER':([8,11,13,14,16,19,22,23,26,35,37,],[12,15,17,18,20,24,27,27,27,27,20,]),'FROM':([9,10,],[13,14,]),'SET':([12,],[16,]),'(':([15,36,],[19,40,]),'WHERE':([17,18,21,32,41,],[22,23,26,-13,-14,]),'=':([20,27,],[25,34,]),')':([24,42,43,46,],[31,44,-10,-11,]),'STRING':([25,34,40,45,],[32,38,43,43,]),'AND':([29,38,],[35,-8,]),'VALUES':([31,],[36,]),',':([32,43,],[37,45,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'select_query':([0,],[2,]),'insert_query':([0,],[3,]),'update_query':([0,],[4,]),'delete_query':([0,],[5,]),'set_values':([16,37,],[21,41,]),'conditions':([22,23,26,35,],[28,30,33,39,]),'condition':([22,23,26,35,],[29,29,29,29,]),'values':([40,45,],[42,46,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> select_query','query',1,'p_query','errores.py',36),
  ('query -> insert_query','query',1,'p_query','errores.py',37),
  ('query -> update_query','query',1,'p_query','errores.py',38),
  ('query -> delete_query','query',1,'p_query','errores.py',39),
  ('select_query -> SELECT * FROM IDENTIFIER WHERE conditions','select_query',6,'p_select_query','errores.py',43),
  ('conditions -> condition','conditions',1,'p_conditions','errores.py',47),
  ('conditions -> condition AND conditions','conditions',3,'p_conditions','errores.py',48),
  ('condition -> IDENTIFIER = STRING','condition',3,'p_condition','errores.py',55),
  ('insert_query -> INSERT INTO IDENTIFIER ( IDENTIFIER ) VALUES ( values )','insert_query',10,'p_insert_query','errores.py',59),
  ('values -> STRING','values',1,'p_values','errores.py',63),
  ('values -> STRING , values','values',3,'p_values','errores.py',64),
  ('update_query -> UPDATE IDENTIFIER SET set_values WHERE conditions','update_query',6,'p_update_query','errores.py',71),
  ('set_values -> IDENTIFIER = STRING','set_values',3,'p_set_values','errores.py',75),
  ('set_values -> IDENTIFIER = STRING , set_values','set_values',5,'p_set_values','errores.py',76),
  ('delete_query -> DELETE FROM IDENTIFIER WHERE conditions','delete_query',5,'p_delete_query','errores.py',83),
]
